"""
    stochastic_forcing_generation

Realization generation: per-step random phases, Hermitian symmetry (CPU loops and
device kernels), and zero-mode handling.

Split out of the former 1767-line `stochastic_forcing.jl`; the sections are
unchanged, only relocated.
"""

# ============================================================================
# Forcing Generation
# ============================================================================

"""
    generate_forcing!(forcing::StochasticForcing, t::Real, substep::Int=1)

Generate stochastic forcing at time t. Works on both CPU and GPU.

## Key Points

1. **Forcing is regenerated only on substep 1** - ensures forcing stays constant
   within a timestep for IMEX and multi-stage methods.

2. **Scaling**: F̂(k) = √Q̂(k) · exp(i·φ) / √dt, where φ ∼ Uniform[0, 2π) (generated by `_fill_random_phases!`)

3. **Zero mean**: The k=0 mode is always set to zero.

4. **Hermitian symmetry** (optional): F̂(-k) = F̂(k)* so that ifft produces real fields.

5. **GPU support**: Random phases are generated on the target architecture when possible,
   then combined with the spectrum using broadcasted operations.

## Arguments

- `forcing`: StochasticForcing configuration
- `t`: Current simulation time
- `substep`: Current substep (1 for first substep)

## Returns

The cached forcing array (modified in-place).
"""
function generate_forcing!(forcing::StochasticForcing{T, N, A, CA}, t::Real, substep::Int=1) where {T, N, A, CA}
    # Only update forcing on first substep
    if substep > 1
        return forcing.cached_forcing
    end

    # Check if we've already updated at this time
    # Use exact equality — isapprox(t, last) with default rtol can freeze forcing
    # at large simulation times because √eps * |t| >> dt
    if t == forcing.last_update_time
        return forcing.cached_forcing
    end

    # Generate forcing using GPU-compatible method
    _generate_forcing_gpu_compatible!(forcing)

    forcing.last_update_time = T(t)
    return forcing.cached_forcing
end

"""
    _generate_forcing_gpu_compatible!(forcing)

GPU-compatible forcing generation using broadcasted operations.
Random phases are generated on the target architecture.
Hermitian symmetry is enforced using array operations when enabled.
"""
function _generate_forcing_gpu_compatible!(forcing::StochasticForcing{T, N, A, CA}) where {T, N, A, CA}
    if forcing.dt <= 0
        error("StochasticForcing requires dt > 0 (got dt=$(forcing.dt)). " *
              "Ensure the timestep is set before generating forcing.")
    end
    sqrt_dt = sqrt(forcing.dt)

    phases = forcing.random_phases
    _fill_random_phases!(forcing.architecture, phases, forcing.rng)

    # Compute forcing: F = spectrum * exp(i*phase) / sqrt(dt)
    # phases ∈ [0,2π) after _fill_random_phases! already scales rand() by 2π
    forcing.cached_forcing .= forcing.forcing_spectrum .* exp.(im .* phases) ./ sqrt_dt

    # Enforce Hermitian symmetry for real physical fields (optional)
    if forcing.enforce_hermitian
        _enforce_hermitian_symmetry!(forcing.cached_forcing, forcing.architecture)
    end

    # Enforce zero mean (k=0 mode)
    _set_zero_mode!(forcing.cached_forcing, forcing.architecture)

    return forcing.cached_forcing
end

function generate_forcing!(forcing::SeparableStochasticForcing{T}, t::Real,
                           substep::Int=1) where T
    substep > 1 && return forcing.cached_forcing
    t == forcing.last_update_time && return forcing.cached_forcing

    forcing.dt > 0 || error(
        "SeparableStochasticForcing requires dt > 0 (got dt=$(forcing.dt)). " *
        "Ensure the timestep is set before generating forcing.",
    )

    _fill_random_phases!(forcing.architecture, forcing.random_phases, forcing.rng)
    sqrt_dt = sqrt(forcing.dt)
    forcing.fourier_realization .= forcing.forcing_spectrum .*
        exp.(im .* forcing.random_phases) ./ sqrt_dt

    if forcing.enforce_hermitian
        _enforce_hermitian_symmetry!(
            forcing.fourier_realization, forcing.architecture,
        )
    end
    _set_zero_mode!(forcing.fourier_realization, forcing.architecture)

    forcing.cached_forcing .= forcing.fourier_outer_view .* forcing.profile_outer_view
    forcing.last_update_time = T(t)
    return forcing.cached_forcing
end

"""
    _enforce_hermitian_symmetry!(data, arch)

Enforce Hermitian symmetry F̂(-k) = F̂(k)* for real physical fields.
GPU uses a kernel-based implementation to avoid device-host transfers.
"""
function _enforce_hermitian_symmetry!(data::AbstractArray{Complex{T}, N}, arch::CPU) where {T, N}
    # CPU implementation using scalar indexing
    if N == 1
        _enforce_hermitian_1d!(data)
    elseif N == 2
        _enforce_hermitian_2d!(data)
    elseif N == 3
        _enforce_hermitian_3d!(data)
    end
end

@kernel function _enforce_hermitian_1d_kernel!(data::AbstractVector{Complex{T}}, n::Int) where {T}
    i = @index(Global, Linear)
    ci = i == 1 ? 1 : n + 2 - i
    if i < ci
        data[ci] = conj(data[i])
    elseif i == ci
        data[i] = Complex{T}(sqrt(T(2)) * real(data[i]), zero(T))
    end
end

@kernel function _enforce_hermitian_2d_kernel!(data::AbstractMatrix{Complex{T}}, nx::Int, ny::Int) where {T}
    I = @index(Global, Cartesian)
    i = I[1]
    j = I[2]
    ci = i == 1 ? 1 : nx + 2 - i
    cj = j == 1 ? 1 : ny + 2 - j

    if (i < ci) || (i == ci && j < cj)
        data[ci, cj] = conj(data[i, j])
    elseif i == ci && j == cj
        data[i, j] = Complex{T}(sqrt(T(2)) * real(data[i, j]), zero(T))
    end
end

@kernel function _enforce_hermitian_3d_kernel!(data::AbstractArray{Complex{T}, 3}, nx::Int, ny::Int, nz::Int) where {T}
    I = @index(Global, Cartesian)
    i = I[1]
    j = I[2]
    k = I[3]
    ci = i == 1 ? 1 : nx + 2 - i
    cj = j == 1 ? 1 : ny + 2 - j
    ck = k == 1 ? 1 : nz + 2 - k

    lin_idx = i + (j - 1) * nx + (k - 1) * nx * ny
    conj_lin_idx = ci + (cj - 1) * nx + (ck - 1) * nx * ny

    if lin_idx < conj_lin_idx
        data[ci, cj, ck] = conj(data[i, j, k])
    elseif lin_idx == conj_lin_idx
        data[i, j, k] = Complex{T}(sqrt(T(2)) * real(data[i, j, k]), zero(T))
    end
end

function _enforce_hermitian_symmetry!(data::AbstractArray{Complex{T}, N}, arch::GPU) where {T, N}
    if N == 1
        n = size(data, 1)
        launch!(arch, _enforce_hermitian_1d_kernel!, data, n; ndrange=n)
    elseif N == 2
        nx, ny = size(data)
        launch!(arch, _enforce_hermitian_2d_kernel!, data, nx, ny; ndrange=size(data))
    elseif N == 3
        nx, ny, nz = size(data)
        launch!(arch, _enforce_hermitian_3d_kernel!, data, nx, ny, nz; ndrange=size(data))
    end
end

"""
    _enforce_hermitian_1d!(data)

Enforce F̂(-k) = F̂(k)* for 1D arrays.
"""
function _enforce_hermitian_1d!(data::AbstractVector{Complex{T}}) where T
    n = length(data)

    # DC mode (k=0) must be real
    data[1] = Complex{T}(sqrt(T(2)) * real(data[1]), zero(T))

    # Nyquist mode (if even n) must be real
    if iseven(n)
        nyq = n ÷ 2 + 1
        data[nyq] = Complex{T}(sqrt(T(2)) * real(data[nyq]), zero(T))
    end

    # Enforce conjugate symmetry: F(-k) = F(k)*
    last_positive = iseven(n) ? n ÷ 2 : (n + 1) ÷ 2
    for i in 2:last_positive
        j = n + 2 - i  # Corresponding negative frequency
        data[j] = conj(data[i])
    end
end

"""
    _enforce_hermitian_2d!(data)

Enforce F̂(-kx, -ky) = F̂(kx, ky)* for 2D arrays.
"""
function _enforce_hermitian_2d!(data::AbstractMatrix{Complex{T}}) where T
    nx, ny = size(data)

    for j in 1:ny
        for i in 1:nx
            # Find conjugate index
            ci = i == 1 ? 1 : nx + 2 - i
            cj = j == 1 ? 1 : ny + 2 - j

            # Only process if we haven't visited this pair yet
            if (i < ci) || (i == ci && j < cj)
                # Keep the primary value so unit-magnitude phases are preserved.
                data[ci, cj] = conj(data[i, j])
            elseif i == ci && j == cj
                # Project to the real axis and preserve the mode's expected power.
                data[i, j] = Complex{T}(sqrt(T(2)) * real(data[i, j]), zero(T))
            end
        end
    end
end

"""
    _enforce_hermitian_3d!(data)

Enforce F̂(-k) = F̂(k)* for 3D arrays.
"""
function _enforce_hermitian_3d!(data::AbstractArray{Complex{T}, 3}) where T
    nx, ny, nz = size(data)

    for k in 1:nz
        for j in 1:ny
            for i in 1:nx
                # Find conjugate index
                ci = i == 1 ? 1 : nx + 2 - i
                cj = j == 1 ? 1 : ny + 2 - j
                ck = k == 1 ? 1 : nz + 2 - k

                # Only process if we haven't visited this pair yet
                lin_idx = i + (j-1)*nx + (k-1)*nx*ny
                conj_lin_idx = ci + (cj-1)*nx + (ck-1)*nx*ny

                if lin_idx < conj_lin_idx
                    # Keep the primary value so unit-magnitude phases are preserved.
                    data[ci, cj, ck] = conj(data[i, j, k])
                elseif lin_idx == conj_lin_idx
                    # Project to the real axis and preserve the mode's expected power.
                    data[i, j, k] = Complex{T}(sqrt(T(2)) * real(data[i, j, k]), zero(T))
                end
            end
        end
    end
end

"""
    _set_zero_mode!(data, arch)

Set the k=0 (DC) mode to zero. GPU-compatible.
"""
function _set_zero_mode!(data::AbstractArray{Complex{T}, N}, arch::CPU) where {T, N}
    data[1] = zero(Complex{T})
end

function _set_zero_mode!(data::AbstractArray{Complex{T}, N}, arch::GPU) where {T, N}
    # For GPU arrays, we need to use fill! with a view or copyto!
    # Using a scalar write that works on GPU via KernelAbstractions pattern
    fill!(view(data, 1:1), zero(Complex{T}))
end

"""
    generate_forcing!(forcing::StochasticForcing, t::Real)

Generate forcing without substep tracking. Equivalent to substep=1.
"""
generate_forcing!(forcing::StochasticForcing, t::Real) = generate_forcing!(forcing, t, 1)

