# Classify the legacy export surface: exported from Tarang but absent from the
# @public_api manifest. Buckets are decided by WHERE each name is referenced.
using Tarang

const ROOT = pwd()
manifest = Set(Tarang.public_api_names())
exported = setdiff(Set(names(Tarang)), Set([:Tarang]))
legacy = sort(collect(setdiff(exported, manifest)); by = string)

"Collect every identifier-ish token appearing in files under `dir` with the given extensions."
function token_index(dir, exts)
    idx = Dict{String, Int}()
    isdir(dir) || return idx
    for (root, _, files) in walkdir(dir), f in files
        any(e -> endswith(f, e), exts) || continue
        # Skip coverage artifacts.
        occursin(".cov", f) && continue
        for m in eachmatch(r"[A-Za-z_][A-Za-z0-9_!]*", read(joinpath(root, f), String))
            idx[m.match] = get(idx, m.match, 0) + 1
        end
    end
    return idx
end

src_idx     = token_index(joinpath(ROOT, "src"),      (".jl",))
test_idx    = token_index(joinpath(ROOT, "test"),     (".jl",))
docs_idx    = token_index(joinpath(ROOT, "docs"),     (".md", ".jl"))
ex_idx      = token_index(joinpath(ROOT, "examples"), (".jl", ".md"))

"Definition sites in src/ don't count as usage; subtract a rough definition allowance."
function bucket(name)
    s = String(name)
    key = startswith(s, "@") ? s[2:end] : s
    nsrc  = get(src_idx,  key, 0)
    ntest = get(test_idx, key, 0)
    ndocs = get(docs_idx, key, 0)
    nex   = get(ex_idx,   key, 0)
    # An exported name appears at least twice in src/: its definition and its
    # `export`/`@public_api` line. More than that means src/ actually uses it.
    used_in_src = nsrc > 2
    if ndocs > 0 || nex > 0
        return (:documented, nsrc, ntest, ndocs, nex)
    elseif ntest > 0
        return (:tested_only, nsrc, ntest, ndocs, nex)
    elseif used_in_src
        return (:internal, nsrc, ntest, ndocs, nex)
    else
        return (:unreferenced, nsrc, ntest, ndocs, nex)
    end
end

rows = [(n, bucket(n)...) for n in legacy]
counts = Dict{Symbol, Int}()
for r in rows; counts[r[2]] = get(counts, r[2], 0) + 1; end

println("legacy exports (exported, not in @public_api manifest): ", length(legacy))
println()
for b in (:documented, :tested_only, :internal, :unreferenced)
    println(rpad(String(b), 14), lpad(get(counts, b, 0), 5))
end
println()

open(joinpath(ROOT, "docs", "legacy_export_inventory.md"), "w") do io
    println(io, "# Legacy export inventory")
    println(io)
    println(io, "Names exported from `Tarang` that are **not** declared in the `@public_api` ")
    println(io, "manifest (`src/api/public/`). Generated by `scripts/classify_exports.jl`.")
    println(io)
    println(io, "| bucket | count | meaning |")
    println(io, "|---|---:|---|")
    println(io, "| documented | $(get(counts,:documented,0)) | referenced in `docs/` or `examples/` — promote to `@public_api`, or stop documenting |")
    println(io, "| tested_only | $(get(counts,:tested_only,0)) | referenced in `test/` but nowhere user-facing — internal; un-export and use `Tarang.name` in tests |")
    println(io, "| internal | $(get(counts,:internal,0)) | used inside `src/` only — un-export |")
    println(io, "| unreferenced | $(get(counts,:unreferenced,0)) | no reference anywhere beyond its definition — dead, delete or un-export |")
    println(io)
    for b in (:documented, :tested_only, :internal, :unreferenced)
        sel = [r for r in rows if r[2] === b]
        isempty(sel) && continue
        println(io, "## ", b, " (", length(sel), ")")
        println(io)
        println(io, "| name | src | test | docs | examples |")
        println(io, "|---|---:|---:|---:|---:|")
        for (n, _, nsrc, ntest, ndocs, nex) in sel
            println(io, "| `", n, "` | ", nsrc, " | ", ntest, " | ", ndocs, " | ", nex, " |")
        end
        println(io)
    end
end
println("wrote docs/legacy_export_inventory.md")
